// GENERATED by build-ext.js — edit proto/*.js and extension/src/ext-main.js instead.
(function () {
'use strict';

// ==== proto/ascii.js ====
// AsciiRenderer — WebGL2 pipeline that turns any TexImageSource (canvas/video/image)
// into ASCII art on its own canvas. Capture-source-agnostic by design: later phases
// feed it a screen-capture <video> instead of the fake scene canvas.

const VS = `#version 300 es
void main() {
  // fullscreen triangle from gl_VertexID, no buffers needed
  vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));
  gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);
}`;

const FS = `#version 300 es
precision highp float;
uniform sampler2D uSrc;      // source frame (mipmapped)
uniform sampler2D uAtlas;    // glyph strip: uGlyphCount slots of uCell px each
uniform vec2  uOutSize;      // output canvas size, px
uniform vec2  uCell;         // cell size, px
uniform vec2  uRectOrigin;   // crop origin in source UV (GL space, v up)
uniform vec2  uRectSize;     // crop size in source UV
uniform float uGlyphCount;
uniform float uLod;          // mip level that averages ~one cell of source
uniform int   uColorMode;    // 0 = mono ink, 1 = per-cell color
uniform vec3  uInk;
uniform vec3  uBg;
uniform float uInvert;       // 0 or 1
uniform sampler2D uText;     // text passthrough layer (output-sized, straight alpha)
uniform float uTextOn;       // 0 or 1
out vec4 outColor;

void main() {
  vec2 px = gl_FragCoord.xy;
  vec2 cellIdx = floor(px / uCell);
  vec2 cellCenter = (cellIdx + 0.5) * uCell / uOutSize;      // 0..1 across output
  vec2 suv = uRectOrigin + cellCenter * uRectSize;           // into source crop
  vec3 c = textureLod(uSrc, suv, uLod).rgb;
  float lum = dot(c, vec3(0.2126, 0.7152, 0.0722));
  lum = mix(lum, 1.0 - lum, uInvert);
  float gi = clamp(floor(lum * uGlyphCount), 0.0, uGlyphCount - 1.0);
  vec2 inCell = fract(px / uCell);
  vec2 atlasUV = vec2((gi + inCell.x) / uGlyphCount, inCell.y);
  float ink = texture(uAtlas, atlasUV).r;
  vec3 inkColor = (uColorMode == 1) ? clamp(c * 1.8, 0.0, 1.0) : uInk;
  vec3 asciiCol = mix(uBg, inkColor, ink);
  // rotoscoped text on top: halo (bg-colored, alpha) knocks out mosaic, fill is text
  vec4 txt = texture(uText, px / uOutSize) * uTextOn;
  outColor = vec4(mix(asciiCol, txt.rgb, txt.a), 1.0);
}`;

function compile(gl, type, src) {
  const sh = gl.createShader(type);
  gl.shaderSource(sh, src);
  gl.compileShader(sh);
  if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
    throw new Error('shader compile: ' + gl.getShaderInfoLog(sh));
  }
  return sh;
}

class AsciiRenderer {
  constructor(canvas) {
    this.canvas = canvas;
    const gl = canvas.getContext('webgl2', { antialias: false, alpha: false });
    if (!gl) throw new Error('WebGL2 not available');
    this.gl = gl;

    const prog = gl.createProgram();
    gl.attachShader(prog, compile(gl, gl.VERTEX_SHADER, VS));
    gl.attachShader(prog, compile(gl, gl.FRAGMENT_SHADER, FS));
    gl.linkProgram(prog);
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
      throw new Error('program link: ' + gl.getProgramInfoLog(prog));
    }
    this.prog = prog;
    this.u = {};
    for (const name of ['uSrc','uAtlas','uOutSize','uCell','uRectOrigin','uRectSize',
                        'uGlyphCount','uLod','uColorMode','uInk','uBg','uInvert',
                        'uText','uTextOn']) {
      this.u[name] = gl.getUniformLocation(prog, name);
    }

    this.vao = gl.createVertexArray();

    this.srcTex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, this.srcTex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);

    this.atlasTex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, this.atlasTex);
    // atlas slots match output cells 1:1, NEAREST keeps glyph pixels crisp
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);

    this.textTex = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, this.textTex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    // 1x1 transparent placeholder so the sampler is always valid
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE,
                  new Uint8Array([0, 0, 0, 0]));

    this.glyphCount = 0;
    this.cellW = 10;
    this.cellH = 10;
    this.charsSorted = '';
  }

  // Build the glyph strip for `charset` at cell size, auto-sorted by ink density so
  // the strip is a luminance ramp regardless of the order the user typed.
  setCharset(charset, cellW, cellH) {
    const chars = [...new Set([...charset])];
    if (chars.length < 2) chars.push(' ', '@');
    this.cellW = cellW;
    this.cellH = cellH;

    const c2d = document.createElement('canvas');
    const ctx = c2d.getContext('2d', { willReadFrequently: true });
    const baseSize = Math.max(6, Math.floor(cellH * 0.95));
    const fontFor = (px) => `${px}px Consolas, "Courier New", monospace`;
    const draw = (order) => {
      c2d.width = order.length * cellW;
      c2d.height = cellH;
      ctx.fillStyle = '#000';
      ctx.fillRect(0, 0, c2d.width, c2d.height);
      ctx.fillStyle = '#fff';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      order.forEach((ch, i) => {
        // fit wide/tall glyphs (Cyrillic caps, block elements) into their slot
        ctx.font = fontFor(baseSize);
        const m = ctx.measureText(ch);
        const gw = Math.max(m.width, 1e-3);
        const gh = Math.max((m.actualBoundingBoxAscent || baseSize * 0.8) +
                            (m.actualBoundingBoxDescent || baseSize * 0.2), 1e-3);
        const s = Math.min(1, (cellW * 0.98) / gw, (cellH * 0.98) / gh);
        if (s < 1) ctx.font = fontFor(Math.max(4, Math.floor(baseSize * s)));
        ctx.fillText(ch, i * cellW + cellW / 2, cellH / 2 + 1);
      });
    };

    draw(chars);
    const img = ctx.getImageData(0, 0, c2d.width, c2d.height).data;
    const density = chars.map((ch, i) => {
      let sum = 0;
      for (let y = 0; y < cellH; y++) {
        const row = (y * c2d.width + i * cellW) * 4;
        for (let x = 0; x < cellW; x++) sum += img[row + x * 4];
      }
      return { ch, sum };
    });
    density.sort((a, b) => a.sum - b.sum);
    const sorted = density.map(d => d.ch);
    draw(sorted);
    this.charsSorted = sorted.join('');
    this.glyphCount = sorted.length;

    const gl = this.gl;
    gl.bindTexture(gl.TEXTURE_2D, this.atlasTex);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, c2d);
  }

  // source: TexImageSource; crop: {x,y,w,h} in source pixels (top-left origin);
  // opts: {colorMode, ink:[r,g,b], bg:[r,g,b], invert, textLayer: TexImageSource|null}
  render(source, srcW, srcH, crop, opts = {}) {
    const gl = this.gl;
    const outW = this.canvas.width, outH = this.canvas.height;

    gl.activeTexture(gl.TEXTURE0);
    gl.bindTexture(gl.TEXTURE_2D, this.srcTex);
    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, source);
    gl.generateMipmap(gl.TEXTURE_2D);

    gl.activeTexture(gl.TEXTURE1);
    gl.bindTexture(gl.TEXTURE_2D, this.atlasTex);

    gl.activeTexture(gl.TEXTURE2);
    gl.bindTexture(gl.TEXTURE_2D, this.textTex);
    if (opts.textLayer) {
      gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, opts.textLayer);
    }

    gl.viewport(0, 0, outW, outH);
    gl.useProgram(this.prog);
    gl.bindVertexArray(this.vao);

    // top-left crop rect -> GL UV space (v up)
    const u0 = crop.x / srcW;
    const v0 = (srcH - (crop.y + crop.h)) / srcH;
    const su = crop.w / srcW;
    const sv = crop.h / srcH;
    // mip level whose texel covers ~one output cell of source pixels
    const lod = Math.log2(Math.max(
      this.cellW * (crop.w / outW),
      this.cellH * (crop.h / outH), 1));

    gl.uniform1i(this.u.uSrc, 0);
    gl.uniform1i(this.u.uAtlas, 1);
    gl.uniform2f(this.u.uOutSize, outW, outH);
    gl.uniform2f(this.u.uCell, this.cellW, this.cellH);
    gl.uniform2f(this.u.uRectOrigin, u0, v0);
    gl.uniform2f(this.u.uRectSize, su, sv);
    gl.uniform1f(this.u.uGlyphCount, this.glyphCount);
    gl.uniform1f(this.u.uLod, lod);
    gl.uniform1i(this.u.uColorMode, opts.colorMode | 0);
    gl.uniform3fv(this.u.uInk, opts.ink || [0.55, 1.0, 0.55]);
    gl.uniform3fv(this.u.uBg, opts.bg || [0.02, 0.04, 0.02]);
    gl.uniform1f(this.u.uInvert, opts.invert ? 1 : 0);
    gl.uniform1i(this.u.uText, 2);
    gl.uniform1f(this.u.uTextOn, opts.textLayer ? 1 : 0);

    gl.drawArrays(gl.TRIANGLES, 0, 3);
  }
}

// ==== proto/presets.js ====
// Charset presets shared by the phase-0 sandbox and the live page.
const PRESETS = {
  ascii10: ' .:-=+*#%@',
  ascii70: " .'`^\",:;Il!i~+_-?][}{1)(|/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$",
  cyrillic: ' .,-:;тлпнсоеавыкзмджчцшщХЖМШЩ@',
  blocks: ' ▁▂▃▄▅▆▇█',
};

// ==== proto/textlayer.js ====
// Paints "rotoscoped" text into a layer canvas: real strings drawn in terminal
// style with a dark knockout halo that suppresses the ASCII mosaic underneath.
// items: [{text, x, y, size, weight}] with y = text baseline, coords in source px.
// crop: {x, y} source-px offset of the visible region.
// scaleX/scaleY: source px -> layer canvas px.
function paintTextLayer(ctx, items, crop, opts = {}) {
  const { scaleX = 1, scaleY = 1, ink = '#8df59a' } = opts;
  const W = ctx.canvas.width, H = ctx.canvas.height;
  ctx.clearRect(0, 0, W, H);
  if (!items) return;
  const cropH = H / scaleY;
  for (const it of items) {
    if (it.y < crop.y - 2 || it.y - it.size > crop.y + cropH + 2) continue;
    const size = Math.max(6, it.size * scaleY);
    ctx.font = `${it.weight ? it.weight + ' ' : ''}${size.toFixed(1)}px Consolas, monospace`;
    ctx.textAlign = 'left';
    ctx.textBaseline = 'alphabetic';
    ctx.lineJoin = 'round';
    ctx.lineWidth = Math.max(2, size / 5);
    ctx.strokeStyle = 'rgba(2, 9, 4, 0.92)';
    const dx = (it.x - crop.x) * scaleX;
    const dy = (it.y - crop.y) * scaleY;
    // monospace is wider than most site fonts — squeeze into the item's real box
    // so neighbouring strings don't run into each other
    let f = 1;
    if (it.w) {
      const m = ctx.measureText(it.text).width;
      const targetW = it.w * scaleX;
      if (m > targetW && m > 0) f = Math.max(0.55, targetW / m);
    }
    if (f < 1) {
      ctx.save();
      ctx.translate(dx, dy);
      ctx.scale(f, 1);
      ctx.strokeText(it.text, 0, 0);
      ctx.fillStyle = ink;
      ctx.fillText(it.text, 0, 0);
      ctx.restore();
    } else {
      ctx.strokeText(it.text, dx, dy);
      ctx.fillStyle = ink;
      ctx.fillText(it.text, dx, dy);
    }
  }
}

// ==== proto/domtext.js ====
// DOM text extraction v2 — the real "rotoscope" source. Recursively walks visible
// elements of a document (shadow DOM included), pruning whole subtrees outside the
// viewport, and returns {text, x, y, size, weight} items in viewport CSS pixels.
// Reads input/textarea values too (they are not text nodes). No OCR anywhere.
const SKIP_TAGS = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEMPLATE', 'TITLE',
  'IFRAME', 'SVG', 'CANVAS', 'VIDEO', 'AUDIO', 'OBJECT', 'EMBED']);
const MARGIN = 40;   // viewport prune margin, px

function extractTextItems(doc, maxItems = 1500) {
  const items = [];
  if (!doc || !doc.body) return items;
  const win = doc.defaultView;
  const vw = win.innerWidth, vh = win.innerHeight;
  const range = doc.createRange();
  const seen = new Set();

  const push = (text, x, y, size, weight, w) => {
    if (!text || items.length >= maxItems) return;
    // dedup: same string at nearly the same spot (visible+aria twins on real sites)
    const key = text + '|' + Math.round(x / 6) + '|' + Math.round(y / 6);
    if (seen.has(key)) return;
    seen.add(key);
    items.push({ text, x, y, size, weight, w });
  };

  const pushRect = (text, r, size, weight) => {
    if (r.width < 1 || r.height < 1) return;
    if (r.bottom < 0 || r.top > vh || r.right < 0 || r.left > vw) return;
    push(text, r.left, r.bottom - size * 0.2, size, weight, r.width);
  };

  function walk(el, depth) {
    if (items.length >= maxItems || depth > 48) return;
    if (SKIP_TAGS.has(el.tagName)) return;

    const r = el.getBoundingClientRect();
    // prune subtrees fully outside the viewport; keep zero-size wrappers (their
    // absolutely-positioned children may still be visible)
    if (r.width > 0 && r.height > 0 &&
        (r.bottom < -MARGIN || r.top > vh + MARGIN || r.right < -MARGIN || r.left > vw + MARGIN)) return;

    const cs = win.getComputedStyle(el);
    if (cs.visibility === 'hidden' || cs.display === 'none' || +cs.opacity === 0) return;
    if ((cs.clip && cs.clip !== 'auto') || (cs.clipPath && cs.clipPath !== 'none')) return;
    const size = parseFloat(cs.fontSize) || 14;
    const weight = (parseInt(cs.fontWeight, 10) || 400) >= 600 ? 'bold' : '';

    // form fields: value/placeholder are not text nodes
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      const isTexty = el.tagName === 'TEXTAREA' ||
        !el.type || ['text', 'search', 'url', 'email', 'tel', 'number', ''].includes(el.type);
      const val = isTexty ? (el.value || el.placeholder) : (el.type === 'submit' || el.type === 'button' ? el.value : '');
      if (val && size >= 6) {
        const padL = parseFloat(cs.paddingLeft) || 2;
        pushRect(String(val).replace(/\s+/g, ' ').slice(0, 300),
          { left: r.left + padL, right: r.right, width: r.width - padL, height: r.height,
            top: r.top, bottom: r.top + (r.height + size * 0.72) / 2 + size * 0.2 },
          size, weight);
      }
      return;
    }

    for (let n = el.firstChild; n; n = n.nextSibling) {
      if (items.length >= maxItems) return;
      if (n.nodeType === 3) {
        if (size < 6) continue;
        const raw = n.nodeValue;
        if (!raw || !raw.trim()) continue;
        range.selectNodeContents(n);
        const rects = range.getClientRects();
        if (rects.length === 1) {
          pushRect(raw.replace(/\s+/g, ' ').trim(), rects[0], size, weight);
        } else if (rects.length > 1) {
          // multi-line node: place word by word so each lands on its own line
          const re = /\S+/g;
          let m;
          while ((m = re.exec(raw)) && items.length < maxItems) {
            range.setStart(n, m.index);
            range.setEnd(n, m.index + m[0].length);
            pushRect(m[0], range.getBoundingClientRect(), size, weight);
          }
        }
      } else if (n.nodeType === 1) {
        walk(n, depth + 1);
      }
    }
    if (el.shadowRoot) {
      for (const c of el.shadowRoot.children) {
        if (c.nodeType === 1) walk(c, depth + 1);
      }
    }
  }

  walk(doc.body, 0);
  return items;
}

// ==== proto/cursor.js ====
// CursorLayer — the pointer rendered inside the ASCII aesthetic: an inverse block
// snapped to the cell grid, whose glyph mirrors the real CSS cursor state, plus a
// short ripple on click. Coordinates are OUTPUT-canvas pixels (callers map).
const GLYPHS = [
  ['pointer', '>'],
  ['text', '|'],
  ['vertical-text', '-'],
  ['grabbing', '%'],
  ['grab', '%'],
  ['not-allowed', 'x'],
  ['no-drop', 'x'],
  ['wait', '~'],
  ['progress', '~'],
  ['crosshair', '+'],
  ['move', '+'],
  ['all-scroll', '+'],
];

class CursorLayer {
  constructor() {
    this.active = false;
    this.x = 0;
    this.y = 0;
    this.css = 'default';
    this.pressed = false;
    this.clickT = -1e9;
    this.clickX = 0;
    this.clickY = 0;
  }

  update(p) { Object.assign(this, p); this.active = true; }
  leave() { this.active = false; }
  press(x, y) { this.pressed = true; this.clickT = performance.now(); this.clickX = x; this.clickY = y; }
  release() { this.pressed = false; }

  glyph() {
    for (const [k, g] of GLYPHS) if (this.css.startsWith(k)) return g;
    return '+';
  }

  draw(ctx, cell, now = performance.now()) {
    if (!this.active) return;
    const cx = Math.floor(this.x / cell) * cell;
    const cy = Math.floor(this.y / cell) * cell;

    // inverse block cell
    ctx.fillStyle = this.pressed ? 'rgba(255, 255, 210, 0.95)' : 'rgba(141, 245, 154, 0.92)';
    ctx.fillRect(cx, cy, cell, cell);
    ctx.fillStyle = '#04120a';
    ctx.font = `bold ${Math.max(6, cell - 1)}px Consolas, monospace`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(this.glyph(), cx + cell / 2, cy + cell / 2 + 0.5);

    // click ripple, ~320ms
    const age = now - this.clickT;
    if (age >= 0 && age < 320) {
      const k = age / 320;
      const rcx = Math.floor(this.clickX / cell) * cell + cell / 2;
      const rcy = Math.floor(this.clickY / cell) * cell + cell / 2;
      ctx.strokeStyle = `rgba(141, 245, 154, ${(1 - k).toFixed(3)})`;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.arc(rcx, rcy, cell * (0.5 + k * 3), 0, Math.PI * 2);
      ctx.stroke();
    }
  }
}

// ==== proto/textgrid.js ====
// Builds the current frame as an actual character grid — the "page as raw text".
// Mirrors the shader's mapping: per-cell luminance (downsampled via drawImage)
// indexed into the density-sorted ramp; rotoscoped text items are stamped into the
// grid one character per cell. Returns an array of row strings.
function buildCharGrid(source, crop, cellW, cellH, outW, outH, ramp, opts = {}) {
  const cols = Math.max(1, Math.floor(outW / cellW));
  const rows = Math.max(1, Math.floor(outH / cellH));
  const c = document.createElement('canvas');
  c.width = cols;
  c.height = rows;
  const x = c.getContext('2d', { willReadFrequently: true });
  x.drawImage(source, crop.x, crop.y, crop.w, crop.h, 0, 0, cols, rows);
  const d = x.getImageData(0, 0, cols, rows).data;
  const N = ramp.length || 1;
  const grid = [];
  for (let r = 0; r < rows; r++) {
    const row = new Array(cols);
    for (let ci = 0; ci < cols; ci++) {
      const i = (r * cols + ci) * 4;
      let lum = (0.2126 * d[i] + 0.7152 * d[i + 1] + 0.0722 * d[i + 2]) / 255;
      if (opts.invert) lum = 1 - lum;
      row[ci] = ramp[Math.min(N - 1, Math.floor(lum * N))] || ' ';
    }
    grid.push(row);
  }
  if (opts.items) {
    const sx = opts.scaleX || 1, sy = opts.scaleY || 1;
    for (const it of opts.items) {
      // baseline -> the row containing the text's visual middle
      const row = Math.floor((it.y * sy - it.size * sy * 0.45) / cellH);
      if (row < 0 || row >= rows) continue;
      let col = Math.floor((it.x * sx) / cellW);
      for (const ch of it.text) {
        if (col >= cols) break;
        if (col >= 0) grid[row][col] = ch;
        col++;
      }
    }
  }
  return grid.map((r) => r.join(''));
}

// ==== extension/src/ext-main.js ====
// ASCII Shader — content-script main. Runs INSIDE the target page (any origin):
// - capture: getDisplayMedia(preferCurrentTab) or tabCapture streamId (promptless
//   experiment), restricted to <body> via Element Capture so the overlay (a sibling
//   of body inside <html>) never enters the stream — no feedback loop
// - input: never intercepted at all — the overlay is pointer-events:none, the page
//   receives real trusted events; we only listen to mirror the cursor in ASCII
// - text rotoscope: extractTextItems(document) — this page's own DOM, any language
// The build script concatenates ascii/presets/textlayer/domtext/cursor before this
// file inside one IIFE; imports below exist for editors and are stripped at build.







if (window.__asciiShader) {
  window.__asciiShader.togglePanel();
} else {
  const state = {
    running: false, mode: 'idle',            // 'overlay' | 'monitor'
    cell: 8, charset: PRESETS.ascii10, colorMode: 0, invert: false,
    textPass: true, cursorOn: true, hideNative: false, textMode: false,
    align: 'auto',                           // 'auto' | 'page' | 'viewport'
    debug: false,
  };
  const VERSION = '0.2.1';
  const isExt = typeof chrome !== 'undefined' && !!(chrome.runtime && chrome.runtime.id);
  const cursor = new CursorLayer();
  let stream = null, domItems = null, domTimer = 0, scrollTimer = 0;
  let renderer = null, emaMs = 16.7, last = performance.now();
  let targetEl = null;   // element the track is restricted to (usually <body>)
  let cropDebug = null;  // last alignment decision, for the debug readout

  // Element Capture frames cover the restricted element's PAINTED bounds — which,
  // depending on the page, may be its border box, the box plus layout overflow
  // (wide images, absolutely-positioned children), or effectively the viewport.
  // Guess which coordinate space the frame is in by matching its aspect ratio
  // against the candidates, then cut the currently visible window out of it so
  // mosaic coords always match DOM/viewport coords. `align` overrides the guess.
  function computeCrop(tr, scrollW, scrollH, vw, vh, iw, ih, align) {
    const full = { x: 0, y: 0, w: vw, h: vh };
    if (!tr || !tr.width || !tr.height || align === 'viewport') return full;
    const cands = [
      { name: 'box', w: tr.width, h: tr.height },
      { name: 'scroll', w: Math.max(tr.width, scrollW || 0), h: Math.max(tr.height, scrollH || 0) },
    ];
    const va = vw / vh;
    let best = cands[0], bestErr = Infinity;
    for (const c of cands) {
      const err = Math.abs(va - c.w / c.h) / va;
      if (err < bestErr) { bestErr = err; best = c; }
    }
    cropDebug = { vw, vh, box: `${Math.round(tr.width)}×${Math.round(tr.height)}@${Math.round(tr.top)}`,
      scroll: `${scrollW}×${scrollH}`, win: `${iw}×${ih}`, pick: best.name, err: +bestErr.toFixed(3) };
    if (align !== 'page' && bestErr > 0.06) {
      // frame aspect matches neither page-space candidate → frames are viewport-mapped
      cropDebug.pick = 'viewport-fallback';
      return full;
    }
    const kx = vw / best.w, ky = vh / best.h;
    let x = Math.max(0, Math.min(-tr.left * kx, vw - 2));
    let y = Math.max(0, Math.min(-tr.top * ky, vh - 2));
    return { x, y, w: Math.min(iw * kx, vw - x), h: Math.min(ih * ky, vh - y) };
  }

  function overlayCropRect() {
    if (state.mode === 'overlay' && targetEl) {
      return computeCrop(targetEl.getBoundingClientRect(),
        targetEl.scrollWidth, targetEl.scrollHeight,
        video.videoWidth, video.videoHeight, innerWidth, innerHeight, state.align);
    }
    return { x: 0, y: 0, w: video.videoWidth, h: video.videoHeight };
  }

  // ---------- DOM nodes (all outside <body> so restrictTo(body) excludes them) ----------
  const root = document.documentElement;
  const video = document.createElement('video');
  video.muted = true;
  video.playsInline = true;

  const canvas = document.createElement('canvas');
  canvas.style.cssText = 'position:fixed;inset:0;width:100vw;height:100vh;' +
    'pointer-events:none;z-index:2147483646;display:none;background:#000;';
  root.appendChild(canvas);

  const textCanvas = document.createElement('canvas');
  const textCtx = textCanvas.getContext('2d');

  const panel = document.createElement('div');
  panel.style.cssText = 'position:fixed;top:10px;right:10px;z-index:2147483647;' +
    'background:#15151cee;color:#ddd;border:1px solid #3a3a45;border-radius:8px;' +
    'padding:10px;font:12px Consolas,monospace;width:250px;pointer-events:auto;' +
    'box-shadow:0 4px 16px #000a;';
  panel.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px">
      <b style="color:#8df59a">ASCII·Shader <span style="opacity:.55;font-weight:normal">v__VER__</span></b>
      <span data-k="fps" style="color:#7fe08a"></span>
    </div>
    <div data-k="st" style="color:#8a8;margin-bottom:8px;line-height:1.4">…</div>
    <div style="display:flex;gap:6px;margin-bottom:8px">
      <button data-k="start" style="flex:1">▶ Старт</button>
      <button data-k="startq" style="flex:1">▶ без диалога</button>
      <button data-k="stopb">■</button>
    </div>
    <div style="display:flex;gap:6px;margin-bottom:8px;align-items:center">
      <select data-k="preset" style="flex:1">
        <option value="ascii10">ASCII 10</option><option value="ascii70">ASCII 70</option>
        <option value="cyrillic">Кириллица</option><option value="blocks">Blocks</option>
      </select>
      <select data-k="mode"><option value="0">mono</option><option value="1">color</option></select>
    </div>
    <div style="display:flex;gap:6px;margin-bottom:8px;align-items:center">
      <span>cell <b data-k="cellv">8</b></span>
      <input data-k="cell" type="range" min="4" max="16" value="8" style="flex:1">
    </div>
    <div style="display:flex;gap:10px;flex-wrap:wrap">
      <label><input data-k="invert" type="checkbox"> inv</label>
      <label><input data-k="text" type="checkbox" checked> текст</label>
      <label><input data-k="cur" type="checkbox" checked> курсор</label>
      <label><input data-k="hidecur" type="checkbox"> скрыть сист.</label>
    </div>
    <div style="display:flex;gap:6px;margin-top:8px;align-items:center">
      <label title="кадр замирает и становится выделяемым текстом; страница отключена; Esc — выход">
        <input data-k="textmode" type="checkbox"> режим текста</label>
      <button data-k="copyall" title="скопировать весь кадр как символы">📋 всё</button>
    </div>
    <div style="display:flex;gap:6px;margin-top:8px;align-items:center">
      <select data-k="align" title="если текст едет относительно мозаики — попробуй переключить">
        <option value="auto">выравнивание: авто</option>
        <option value="page">страница</option>
        <option value="viewport">вьюпорт</option>
      </select>
      <label><input data-k="debug" type="checkbox"> debug</label>
    </div>`;
  panel.innerHTML = panel.innerHTML.replace('__VER__', VERSION);
  root.appendChild(panel);
  const $ = (k) => panel.querySelector(`[data-k="${k}"]`);
  panel.querySelectorAll('button,select').forEach((el) => {
    el.style.cssText += 'background:#23232c;color:#ddd;border:1px solid #3a3a45;border-radius:4px;padding:4px 6px;cursor:pointer;';
  });
  const setStatus = (s) => { $('st').textContent = s; };

  // ---------- capture ----------
  function pickTarget() {
    const br = document.body.getBoundingClientRect();
    if (br.width >= innerWidth * 0.9 && br.height >= innerHeight * 0.9) return document.body;
    // rare SPA case: body collapsed — wrap its children so the box covers the page
    let wrap = document.getElementById('__ascii_wrap');
    if (!wrap) {
      wrap = document.createElement('div');
      wrap.id = '__ascii_wrap';
      while (document.body.firstChild) wrap.appendChild(document.body.firstChild);
      document.body.appendChild(wrap);
    }
    return wrap;
  }

  async function start(promptless) {
    if (state.running) stop(false, true);
    try {
      if (promptless) {
        if (!isExt) throw new Error('доступно только внутри расширения');
        const resp = await chrome.runtime.sendMessage({ cmd: 'streamId' });
        if (!resp || !resp.id) throw new Error((resp && resp.err) || 'streamId недоступен');
        stream = await navigator.mediaDevices.getUserMedia({
          audio: false,
          video: { mandatory: { chromeMediaSource: 'tab', chromeMediaSourceId: resp.id } },
        });
      } else {
        stream = await navigator.mediaDevices.getDisplayMedia({
          video: { frameRate: { ideal: 60 } }, audio: false, preferCurrentTab: true,
        });
      }
    } catch (e) {
      setStatus('захват не удался: ' + (e.message || e.name));
      return false;
    }
    const [track] = stream.getVideoTracks();
    const target = pickTarget();
    targetEl = target;
    target.style.isolation = 'isolate';
    state.mode = 'monitor';
    if (typeof RestrictionTarget !== 'undefined' && track.restrictTo) {
      try {
        await track.restrictTo(await RestrictionTarget.fromElement(target));
        state.mode = 'overlay';
      } catch (e) { console.warn('[ascii-shader] restrictTo:', e); }
    }
    if (state.mode !== 'overlay' && typeof CropTarget !== 'undefined' && track.cropTo) {
      try { await track.cropTo(await CropTarget.fromElement(target)); } catch (e) {}
    }
    track.addEventListener('ended', () => stop(true));
    video.srcObject = stream;
    await video.play();
    state.running = true;
    layout();
    applyHideNative();
    startDomWatch();
    setStatus(state.mode === 'overlay'
      ? `оверлей поверх страницы${promptless ? ' · без диалога' : ''} · ввод нативный`
      : 'restrictTo недоступен → монитор в углу (страница видна как есть)');
    return true;
  }

  // one-click-less chain for auto-enabled tabs: try tabCapture first, then ask
  async function autoStart() {
    if (state.running) return;
    if (isExt && await start(true)) { panel.style.display = 'none'; return; }
    panel.style.display = '';
    setStatus((($('st').textContent || '') + ' · автозапуск без диалога не прошёл — нажми ▶ Старт').trim());
  }

  // ---------- text mode: the frozen frame as selectable raw characters ----------
  let pre = null, lastGrid = null;

  function currentGrid() {
    if (!state.running || video.readyState < 2 || !video.videoWidth) return null;
    const s = scales();
    return buildCharGrid(video, overlayCropRect(),
      state.cell, state.cell, canvas.width, canvas.height,
      renderer ? renderer.charsSorted : state.charset, {
        invert: state.invert,
        items: state.textPass ? domItems : null,
        scaleX: s.x, scaleY: s.y,
      });
  }

  function enterTextMode() {
    const grid = currentGrid();
    if (!grid) { $('textmode').checked = false; setStatus('режим текста: сначала запусти захват'); return; }
    lastGrid = grid;
    state.textMode = true;
    const r = canvas.getBoundingClientRect();
    const meas = document.createElement('canvas').getContext('2d');
    meas.font = `${state.cell}px Consolas, monospace`;
    const adv = meas.measureText('M').width || state.cell * 0.55;
    pre = document.createElement('pre');
    pre.id = '__ascii_pre';
    pre.textContent = grid.join('\n');
    pre.style.cssText = `position:fixed;left:${r.left}px;top:${r.top}px;width:${r.width}px;height:${r.height}px;` +
      `margin:0;overflow:hidden;white-space:pre;background:#050b05;color:#8df59a;` +
      `font:${state.cell}px/${state.cell}px Consolas,monospace;letter-spacing:${(state.cell - adv).toFixed(2)}px;` +
      'z-index:2147483646;pointer-events:auto;user-select:text;cursor:text;';
    const sel = document.createElement('style');
    sel.textContent = '#__ascii_pre::selection{background:#2f5c39;color:#fff}';
    pre.appendChild(sel);
    root.appendChild(pre);
    canvas.style.visibility = 'hidden';
    setStatus('режим текста: кадр заморожен, выделяй и копируй · Esc — выход');
  }

  function exitTextMode() {
    state.textMode = false;
    if (pre) { pre.remove(); pre = null; }
    canvas.style.visibility = '';
    if (state.running) setStatus('оверлей · живой рендер продолжен');
  }

  async function copyAll() {
    const grid = state.textMode ? lastGrid : currentGrid();
    if (!grid) { setStatus('копировать нечего — захват не запущен'); return; }
    const text = grid.join('\n');
    try {
      await navigator.clipboard.writeText(text);
      setStatus(`скопировано: ${grid.length} строк × ${grid[0].length} символов`);
    } catch (e) {
      setStatus('clipboard не дался: ' + (e.message || e.name));
    }
  }

  addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && state.textMode) {
      $('textmode').checked = false;
      exitTextMode();
    }
  }, { capture: true });

  function stop(byTrack, internal) {
    if (state.textMode) { const cb = $('textmode'); if (cb) cb.checked = false; exitTextMode(); }
    state.running = false;
    if (stream) { for (const t of stream.getTracks()) t.stop(); stream = null; }
    video.srcObject = null;
    canvas.style.display = 'none';
    clearInterval(domTimer);
    domItems = null;
    root.style.cursor = '';
    if (internal) return;
    panel.style.display = '';
    setStatus(byTrack ? 'шаринг остановлен со стороны браузера' : 'остановлено');
  }

  // ---------- layout / render ----------
  function layout() {
    if (!state.running) return;
    if (state.mode === 'overlay') {
      canvas.style.cssText = 'position:fixed;inset:0;width:100vw;height:100vh;display:block;' +
        'pointer-events:none;z-index:2147483646;background:#000;';
      canvas.width = innerWidth;
      canvas.height = innerHeight;
    } else {
      const w = Math.round(innerWidth * 0.45);
      const h = Math.round(w * (video.videoHeight || 9 * 40) / (video.videoWidth || 16 * 40));
      canvas.style.cssText = 'position:fixed;inset:auto;right:10px;bottom:10px;display:block;' +
        `width:${w}px;height:${h}px;pointer-events:none;z-index:2147483646;background:#000;` +
        'border:1px solid #3a3a45;border-radius:6px;';
      canvas.width = w;
      canvas.height = h;
    }
    textCanvas.width = canvas.width;
    textCanvas.height = canvas.height;
    if (!renderer) renderer = new AsciiRenderer(canvas);
    renderer.setCharset(state.charset, state.cell, state.cell);
  }
  addEventListener('resize', layout, { passive: true });

  function scales() {
    return state.mode === 'overlay'
      ? { x: 1, y: 1 }
      : { x: canvas.width / innerWidth, y: canvas.height / innerHeight };
  }

  function tick(t) {
    emaMs = emaMs * 0.92 + (t - last) * 0.08;
    last = t;
    if (state.running && !state.textMode && video.readyState >= 2 && video.videoWidth) {
      const s = scales();
      const items = state.textPass ? domItems : null;
      const useCursor = state.cursorOn && cursor.active;
      const layerOn = !!items || useCursor;
      if (layerOn) {
        if (items) paintTextLayer(textCtx, items, { x: 0, y: 0 }, { scaleX: s.x, scaleY: s.y });
        else textCtx.clearRect(0, 0, textCanvas.width, textCanvas.height);
        if (useCursor) cursor.draw(textCtx, state.cell, t);
      }
      renderer.render(video, video.videoWidth, video.videoHeight, overlayCropRect(), {
        colorMode: state.colorMode, invert: state.invert,
        ink: [0.55, 1.0, 0.55], bg: [0.02, 0.045, 0.02],
        textLayer: layerOn ? textCanvas : null,
      });
      $('fps').textContent = `${(1000 / emaMs).toFixed(0)} fps`;
      if (state.debug && cropDebug && (t - (tick._dbgT || 0)) > 500) {
        tick._dbgT = t;
        setStatus(`dbg v:${cropDebug.vw}×${cropDebug.vh} body:${cropDebug.box} ` +
          `scroll:${cropDebug.scroll} win:${cropDebug.win} dpr:${devicePixelRatio} ` +
          `pick:${cropDebug.pick} err:${cropDebug.err} align:${state.align} mode:${state.mode}`);
      }
    }
    requestAnimationFrame(tick);
  }

  // ---------- text rotoscope ----------
  function refreshDom() { domItems = extractTextItems(document); }
  function startDomWatch() {
    refreshDom();
    clearInterval(domTimer);
    domTimer = setInterval(() => { if (state.running) refreshDom(); }, 700);
  }
  addEventListener('scroll', () => {
    if (!state.running) return;
    clearTimeout(scrollTimer);
    scrollTimer = setTimeout(refreshDom, 120);
  }, { passive: true, capture: true });

  // ---------- cursor mirror (listeners only — input itself stays native) ----------
  function resolveCursor(el) {
    try {
      const cs = getComputedStyle(el).cursor;
      if (cs && cs !== 'auto') return cs;
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') return 'text';
      if (el.closest && el.closest('a, button, [role=button], summary, label')) return 'pointer';
      return 'default';
    } catch { return 'default'; }
  }
  addEventListener('mousemove', (e) => {
    const s = scales();
    cursor.update({ x: e.clientX * s.x, y: e.clientY * s.y, css: resolveCursor(e.target) });
  }, { passive: true, capture: true });
  addEventListener('mousedown', (e) => {
    const s = scales();
    cursor.press(e.clientX * s.x, e.clientY * s.y);
  }, { passive: true, capture: true });
  addEventListener('mouseup', () => cursor.release(), { passive: true, capture: true });
  root.addEventListener('mouseleave', () => cursor.leave(), { passive: true });

  function applyHideNative() {
    root.style.cursor = (state.running && state.hideNative && state.mode === 'overlay') ? 'none' : '';
  }

  // ---------- controls ----------
  $('start').addEventListener('click', () => start(false));
  $('startq').addEventListener('click', () => start(true));
  if (!isExt) { $('startq').disabled = true; $('startq').title = 'только внутри расширения'; }
  $('stopb').addEventListener('click', () => {
    stop(false);
    if (isExt) chrome.runtime.sendMessage({ cmd: 'disable' }).catch(() => {});
  });
  $('preset').addEventListener('change', (e) => {
    state.charset = PRESETS[e.target.value] || PRESETS.ascii10;
    if (renderer) renderer.setCharset(state.charset, state.cell, state.cell);
  });
  $('mode').addEventListener('change', (e) => { state.colorMode = +e.target.value; });
  $('cell').addEventListener('input', (e) => {
    state.cell = +e.target.value;
    $('cellv').textContent = state.cell;
    if (renderer) renderer.setCharset(state.charset, state.cell, state.cell);
  });
  $('invert').addEventListener('change', (e) => { state.invert = e.target.checked; });
  $('text').addEventListener('change', (e) => { state.textPass = e.target.checked; });
  $('cur').addEventListener('change', (e) => { state.cursorOn = e.target.checked; });
  $('hidecur').addEventListener('change', (e) => { state.hideNative = e.target.checked; applyHideNative(); });
  $('textmode').addEventListener('change', (e) => { e.target.checked ? enterTextMode() : exitTextMode(); });
  $('copyall').addEventListener('click', copyAll);
  $('align').addEventListener('change', (e) => { state.align = e.target.value; });
  $('debug').addEventListener('change', (e) => { state.debug = e.target.checked; if (!state.debug) setStatus(''); });

  if (isExt) {
    chrome.runtime.onMessage.addListener((msg) => {
      if (!msg) return;
      if (msg.cmd === 'autostart') autoStart();
      if (msg.cmd === 'stopcmd') stop(false);
    });
  }

  window.__asciiShader = {
    togglePanel() { panel.style.display = panel.style.display === 'none' ? '' : 'none'; },
    stop, state, cursor, autoStart, computeCrop,
    probe() {
      return {
        restrictTo: typeof RestrictionTarget !== 'undefined',
        cropTo: typeof CropTarget !== 'undefined',
        getDisplayMedia: !!(navigator.mediaDevices && navigator.mediaDevices.getDisplayMedia),
        isExt,
        textItems: extractTextItems(document).length,
      };
    },
  };

  const p = window.__asciiShader.probe();
  setStatus(`готов · текст: ${p.textItems} эл. · restrictTo: ${p.restrictTo ? 'да' : 'нет'}` +
    (isExt ? '' : ' · режим теста (без chrome.*)'));
  requestAnimationFrame(tick);
}

})();
