// Bundles the proto modules + extension/src/ext-main.js into extension/content.js
// (one classic-script IIFE — MV3 content scripts can't use ES module imports).
// Also drops a copy at proto/content.build.js so the dev page can smoke-test it.
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const FILES = [
  'proto/ascii.js',
  'proto/presets.js',
  'proto/textlayer.js',
  'proto/domtext.js',
  'proto/cursor.js',
  'proto/textgrid.js',
  'extension/src/ext-main.js',
];

let out = '// GENERATED by build-ext.js — edit proto/*.js and extension/src/ext-main.js instead.\n' +
  '(function () {\n\'use strict\';\n';
for (const f of FILES) {
  let src = fs.readFileSync(path.join(ROOT, f), 'utf8');
  src = src.replace(/^import .*$/gm, '');
  src = src.replace(/^export (class|function|const)/gm, '$1');
  out += `\n// ==== ${f} ====\n${src}`;
}
out += '\n})();\n';

fs.writeFileSync(path.join(ROOT, 'extension/content.js'), out);
fs.writeFileSync(path.join(ROOT, 'proto/content.build.js'), out);
console.log(`bundled ${FILES.length} files -> extension/content.js (${(out.length / 1024).toFixed(1)} KB)`);
